name: Build Mod
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Make gradlew executable
        run: chmod +x "./快遞礦車項目/gradlew"
        
      - name: Build with Gradle
        run: ./gradlew build
        working-directory: "./快遞礦車項目"

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: FastMinecart-Mod
          path: "./快遞礦車項目/build/libs/*.jar"
